backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
    - name: "index"
      label: "Homepage"
      files:
        - label: "Who I Am File Content"
          name: "who-i-am-file-content"
          file: "data/whoiam.yml"
          fields: 
            - {label: "Content", name: "content", widget: "markdown"}
            - {label: "Image", name: "image", widget: "image"}
        - label: "Services File Content"
          name: "services-file-content"
          file: "data/services.yml"
          fields:
            - {label: "Stump Grinding", name: "stumpGrindingContent", widget: "markdown"}
            - {label: "Tree Pruning", name: "treePruningContent", widget: "markdown"}
            - {label: "Tree Removal", name: "treeRemovalContent", widget: "markdown"}
            - {label: "Bonsai", name: "bonsaiContent", widget: "markdown"}
        - label: "Projects File Content"
          name: "projects-file-content"
          file: "data/projects.yml"
          fields:
            - {label: "Project 1", name: "project1Content", widget: "markdown"}
            - {label: "Project 2", name: "project2Content", widget: "markdown"}
        - name: "contact-me-file-content"
          label: "Contact Me File Content"
          file: "data/contactme.yml"
          fields:
            - {name: "contactContent", label: "Contact Me Content", widget: "markdown"}
                